############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "News"
url = "news/"
weight = 2

[[main]]
name = "Biography"
url = "about/"
weight = 3

[[main]]
name = "Awards"
url = "awards/"
weight = 4

[[main]]
name = "Publications"
url = "awards/"
weight = 5

[[main]]
name = "Talks"
url = "awards/"
weight = 6

[[main]]
name = "Misc."
url = "misc/"
weight = 7



# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
