############# English navigation ##############

# main menu
[[main]]
name = "HOME"
url = "/"
weight = 1

[[main]]
name = "NEWS"
url = "#news"
weight = 2

[[main]]
name = "BIOGRAPHY"
url = "#biography"
weight = 3

[[main]]
name = "PUBLICATIONS"
url = "#publications"
weight = 5

[[main]]
name = "TALKS"
url = "#talks"
weight = 6

[[main]]
name = "MISC."
url = "#misc"
weight = 7



# footer menu
[[footer]]
name = "About"
url = "https://wangxu.ai/#biography"
weight = 1

[[footer]]
name = "GIX"
url = "https://gix.tsinghua.edu.cn/"
weight = 2

[[footer]]
name = "Template"
url = "https://hugoplate.netlify.app/"
weight = 3

