title: Networking and HCI Conference Deadlines
description: Countdowns to top Networking and HCI conference deadlines.
author: Xu Wang

domain: ""
baseurl: "https://wangxu.ai/ddl/"
# Use this baseurl for local testing with `jekyll serve`
# baseurl: ""

twitter_username: nothing
github_username: xu-wang11
github_repo: norepo

markdown: kramdown

